version: '3.9'

services:
  backend:
    image: backend:alpha
    container_name: backend
    restart: unless-stopped
    networks:
      - net
    ports:
      - 44378:80

networks:
  net:
    name: net
    external: true